Fix syntax typo in `version-check` and create a composite `install-meridian` action
PiperOrigin-RevId: 722887853

diff --git a/.github/actions/version-check/action.yml b/.github/actions/version-check/action.yml
--- a/.github/actions/version-check/action.yml
+++ b/.github/actions/version-check/action.yml
@@ -1,6 +1,5 @@
 # Check if the current `meridian.__version__` semver has been incremented. If so, set a
 # `new_version` output.
-name: Version check
 
 inputs:
   python_version:
@@ -9,32 +8,37 @@ inputs:
     default: 3.11
 
 outputs:
-  description: 'The new version if Meridian's semver was incremented, otherwise an empty string.'
-  new_version: ${{ steps.version_check.outputs.new_version }}
+  new_version:
+    description: The new version if Meridian's semver was incremented, otherwise an empty string.
+    value: ${{ steps.version_check.outputs.new_version }}
 
 runs:
-  using: "composite"
+  using: composite
   steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0  # Important: fetch all tags for comparison
-    # Install deps
-    - uses: actions/setup-python@v5
+        fetch-tags: true
+    - uses: ./.github/actions/install-meridian
       with:
-        python-version: ${{ inputs.python_version }}
-        cache: pip
-        cache-dependency-path: '**/pyproject.toml'
-    - shell: bash
-      run: pip install -e . --config-settings editable_mode=strict
+        python_version: ${{ inputs.python_version }}
     - shell: bash
       run: pip install semver
     - id: version_check
       name: Check Version
       shell: bash
-      # !! This relies on the git repository having "v{major}.{minor}.{patch}" named tags.
+      # This relies on the git repository having "v{major}.{minor}.{patch}" named tags.
       run: |
         CURRENT_VERSION=$(python3 -c "import meridian; print(meridian.__version__)")
-        PREVIOUS_TAG=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || echo "v0.0.0")
+
+        # Validate CURRENT_VERSION using semver check
+        if ! python3 -m semver check "$CURRENT_VERSION"; then
+          echo "Error: Invalid semantic version: $CURRENT_VERSION"
+          exit 1 # Fail fast
+        fi
+
+        #PREVIOUS_TAG=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || echo "v0.0.0")
+        PREVIOUS_TAG=$(git describe --tags --abbrev=0 --match 'v*' || { echo "Error: No matching previous tag found." >&2; exit 1; })
         PREVIOUS_VERSION=$(echo "$PREVIOUS_TAG" | sed 's/^v//')
 
         echo "CURRENT_VERSION: $CURRENT_VERSION"
